### ISSUE TITLE
hubert pretrain and finetune

### ISSUE THREAD

**Issue by GUOhm230** [yanghaha0908/FastHuBERT#6]
作者您好：
看您名字，应该是中国人。我就不用英语请教了。您的论文很有意义，让我受益匪浅。因此冒昧提问，多有打扰，还请海涵。
我是一名研二学生，目前正在尝试调试hubert预训练和微调工程，目前希望能达到作者给定的效果。
但是我目前第二次迭代训练的loss经过几个epoch之后一直从8到11基本不变。而用第二次迭代的模型去微调，训练损失在900多一开始。
所以想请教您微调hubert的流程和方法。

**Comment by yanghaha0908** [comment]
如果“第二次迭代训练的loss经过几个epoch之后一直从8到11基本不变”，跟我的训练过程对比的话，这个loss有点高，可以看看repo里的wandb，loss在2-4左右。
我将上传一个我当时微调的脚本和log，是基于只预训练了20个epoch的ckpt微调的，你可以参考一下。

----- 原始邮件 -----
发件人: "GUOhm230" ***@***.***>
收件人: "yanghaha0908/FastHuBERT" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期六, 2024年 11 月 16日 下午 8:46:05
主题: [yanghaha0908/FastHuBERT] hubert pretrain and finetune (Issue #6)

作者您好：
看您名字，应该是中国人。我就不用英语请教了。您的论文很有意义，让我受益匪浅。因此冒昧提问，多有打扰，还请海涵。
我是一名研二学生，目前正在尝试调试hubert预训练和微调工程，目前希望能达到作者给定的效果。
但是我目前第二次迭代训练的loss经过几个epoch之后一直从8到11基本不变。而用第二次迭代的模型去微调，训练损失在900多一开始。
所以想请教您微调hubert的流程和方法。

-- 
Reply to this email directly or view it on GitHub:
https://github.com/yanghaha0908/FastHuBERT/issues/6
